este/este

- src/server/config.js
- src/server/render.js
When an id is configured it will appear at the end of the body.
Otherwise nothing changes.
> Add Google Analytics

- webpack/build.js
This project is amazing - thanks!
> convert tabs into spaces

- src/client/components/todos/index.jsx
- src/client/todos/actions.js
- src/client/todos/store.js
- src/server/express.js
- src/server/html.jsx
- src/server/index.js
- src/server/initialstate.js
- src/server/render.js
> convert relevant lets and vars to const

- README.md
- src/server/index.js
> update readme for auth

- src/client/components/notfound.js
- src/client/messages.js
- don't use template strings - back ticks
- don't use js strings - single quotes
> Cleanup not found page

- README.md
There are no dev deps and never will be. ;-)
> There are no dev deps

- src/server/render.js
> Pass the full url including the get parameters to react-router

- .gitignore
- src/client/auth/actions.js
- src/client/auth/store.js
- src/client/messages.js
- src/client/pages/home.react.js
- src/client/pages/login.react.js
- src/client/pages/me.react.js
- src/client/pages/todos.react.js
- src/client/user/store.js
All issues grouped in the commits
> Several issues fixed

- package.json
- src/server/config.js
> Better config

- src/client/app/app.react.js
- src/client/app/menu.react.js
- src/client/auth/actions.js
- src/client/intl/store.js
- src/client/messages.js
- src/client/pages/home.react.js
- src/client/pages/tocheck.react.js
- src/client/pages/tocheckitem.react.js
I've finished the internationalization of messages in the app. I'm not sure, if I'm using FormattedHTMLMessage in proper way to get HTML messages. Based on my experience is using HTML directly in translation file very usefull (at least for br, strong, b, i, sup, links and anchors). I've added "msgArray" function to Intl store, which can prepare array of messages for easy generation of lists in React components. This is very nice feature, by my opinion. Our company translates to 9 languages and it's amazing to be able to add download links or menu links directly to translation file based on the texts or documents which you got already back and corrected. Feel free to correct me or suggest different solution.
> Internationalization finished.

- package.json
- src/server/express.js
- src/server/render.js
> Added custom state

- webpack/makeconfig.js
> Fix 404 static error in production mode

- webpack/makeconfig.js
Old string entry point (app - production) replaced with new path.join and constants.SRC_DIR.
> Entry point fix

- src/server/lib/errorhandler.js
- src/server/main.js
> Display formatted error page when error occurs during server rendering

- src/server/frontend/index.js
- src/server/frontend/userstate.js
I found out that in all projects that we base on Este we need to fetch some part of initialState from external sources or it has to be specific for the user (A/B tests for example).
This refactoring makes it easier to add new "loader" function which returns returns object that is then merged with the rest of the initial state.
What do you think?
> Extract and refactor loading of parts of state for a user

- src/client/auth/index.react.js
- src/client/examples/index.react.js
- src/client/home/index.react.js
- src/client/me/index.react.js
- src/client/routes.js
- src/client/todos/index.react.js
More intuitive naming of handler component.
> rename feature/page.react.js to feature/index.react.js

- src/server/frontend/render.js
> Define webpack host config using request hostname. Fixes #357

- README.md
> Use SVG icons in readme

- src/client/app/store.js
- src/client/auth/store.js
- src/client/intl/store.js
- src/client/todos/store.js
- src/client/users/store.js
If no action is present it is better to return from store function because you can have undefined in case statement (think about typo in action name).
> Terminate execution of store when no action is present

- src/client/todos/todos.react.js
It`s possible use short syntax of spread operator in this place.
> Apply short syntax , use spread operator in Todo component

- README.md
I'm quite interested in feedback! The idea is to simply show how we to use Este, it doesn't aim to explain how it works (that will go in the wiki). It's really simple, but it can make a good entry point for people, and having people feeling comfortable when searching for a project is definitely a good thing!
> Add este in 1 minute to the readme

- karma.conf.js
Issue #422
Issue already reported in karma-coverage repo
https://github.com/karma-runner/karma-coverage/issues/184
> Disable coverage generation #422

- package.json
- src/client/app/store.js
- src/client/auth/store.js
- src/client/intl/store.js
- src/client/lib/flux/flux.js
- src/client/lib/flux/flux.react.js
- src/client/todos/store.js
- src/client/users/store.js
- src/server/frontend/index.js
Invariants
Named stores for easier debugging
Few tweaks regarding optional parameters
Top level `app` store for global settings passed from server
> Invariants and other tweaks

- package.json
- webpack/makeconfig.js
https://github.com/este/este/issues/437
> Replace autoprefixer-loader

- circle.yml
- package.json
- web/package.json
> Master is no longer broken :)

- common/src/app/mapStateToProps.js
- common/src/app/reducer.js
- common/src/configureStore.js
- common/src/device/reducer.js
- common/src/lib/stateToJS.js
- web/src/client/main.js
> Use combineReducers instead of manual composition of stores

- common/src/auth/reducer.js
- common/src/device/reducer.js
- common/src/intl/reducer.js
- common/src/todos/reducer.js
- common/src/users/reducer.js
In previous version of Flux implementation it was done the same way - see #405
This is easier to read and understand IMO.
> Return from reducer immediately when returning initial state

- common/src/intl/messages/en.js
It will be handled by Redux DevTools
> Remove message about serializing and deserializing appState

- web/gulpfile.babel.js
- web/package.json
- web/src/server/frontend/index.js
- web/src/server/frontend/render.js
- web/src/server/index.js
- web/src/server/main.js
- web/webpack/constants.js
- web/webpack/makeConfig.js
- web/webpack/server/index.js
- web/webpack/server/main.js
Separate server in webpack/server. All is reloadable now.
Given the fact I've already tweaked Gulpfile, decided to clean it up a bit before we continue improving it. Deleted comments are not an issue since we can always look them back (there's previous Este as a release here).
Also, speaking karma wise, I think this task should be completely separated since some users tend to not use it on daily basis.
> Hot-reloadable everything

- package.json
- src/common/auth/actions.js
Updated redux-promise-middleware to version 1.0.0 which adds meta to rejected action
> Updated redux-promise-middleware to version 1.0.0

- package.json
- src/common/fetch.js
> Fix fetch url parse error with double-slash

- app.json
- src/common/fetch.js
> Fix #529 and parse fetch url error with https

- package.json
Version 1.8 does not work for Este
> Downgrade to Nodemon 1.7.3

- src/common/configureStore.js
Adding [Redux Dev Tools](https://github.com/gaearon/redux-devtools) with [Redux Slider Monitor](https://github.com/calesce/redux-slider-monitor) 
Default is visible: none but you can invoke it by `Ctrl+H`
This will be shown not in production
> Add Redux DevTools

- .eslintrc
- package.json
- src/native/app/Menu.react.js
- src/server/config.js
- webpack/constants.js
#588 Fixing all import problems except one with `src/native/app/Menu.react.js` pls @steida or @grabbou fix it I have no idea where Dimensions comes from:  `Unable to resolve path to module 'Dimensions' `
> Add Eslint Plugin Import

- gulpfile.babel.js
Run one specific test file:
```
gulp mocha-file --file src/browser/components/__test__/Button.js
```
Run directory with test files:
```
gulp mocha-file --file 'src/browser/components/__test__/*.js'
```
> Enable to run single test file using gulp mocha-file

- src/server/frontend/render.js
resolve #636 as described in https://github.com/nfl/react-helmet#server-usage
> Fixed problem with Helmet.rewind() and concurrent requests

- src/server/frontend/render.js
Reducer should take care of this.
#629
> Do not throw error on failed fetchActions

- src/common/todos/actions.js
Todos do not load on react native or in mobile view due to complete URL resolving to http://localhost:8000api/v1/todos/user with process.env.WEB_ADDR not set and using default URL
> relative url should be prefixed with a /

- src/browser/todos/Todos.react.js
empty matches intl translation key
> fix empty message

- src/common/intl/messages/index.js
Some people are sometimes reading comments. Yay! ;)
> Fix tiny typos in src/common/intl/messages/index.js.

- .dockerignore
- Dockerfile
- circle.yml
- package.json
> Adds docker support and updates build

- src/server/frontend/render.js
single route may have multi components
eg. https://github.com/reactjs/react-router/blob/master/examples/sidebar/app.js
```js
<Route path="category/:category" components={{ content: Category, sidebar: CategorySidebar }}>
<Route path=":item" component={Item} />
</Route>
```
> Fix server render bug

- src/browser/todos/Todo.react.js
- src/browser/todos/Todo.scss
- src/browser/todos/Todos.react.js
Add toggle of todo in browser
(That is what todos are for, right?)
Remove some unused CSS.
> Toggle todo in browser

- src/common/configureStore.js
- src/common/device/reducer.js
- src/server/frontend/render.js
Partially solve https://github.com/este/este/issues/714
`SERVER_URL` still needs to be set for React Native
> Autoset Heroku URL

- src/common/lib/redux-fields/fields.js
This is a baby PR.
Checkbox state was completely ignored.
> Send checkbox state to the store

- .eslintrc
- package.json
https://github.com/babel/babel-eslint/issues/267
fixes #760
> Pins eslint version and overrides stateless rule

- README.md
> Unify badges, add license badge

- src/server/frontend/render.js
createRoutes(store.getState) on server is now the same as in browser.
> unified createRoutes() on frontend and server

- messages/fr.js
- messages/ro.js
- src/browser/main.js
- src/server/config.js
German version is not part of the PR yet, because my native German-speaking colleague won't be able to check the file before the end of the week.
> Add French and Romanian translations

- package.json
- src/browser/todos/Todos.react.js
- src/browser/todos/__test__/Todo.react.spec.js
- src/browser/todos/__test__/Todos.react.spec.js
Closes #759. I wrote simple cases, with examples with both shallow-rendering and full dom rendering.
> Add examples of tests with enzyme

- messages/de.js
- src/browser/main.js
- src/server/config.js
A promise made is a promise kept.
Don't be frightened, I'm done with translations now :)
> Add German translation

- messages/ro.js
Hey, this is my first pull request so I hope it is useful. I have added translations for the firebase strings into Romanian. I noticed a few mistakes with some of the other translations which I will fix when I get time. Just trying to keep this commit atomic =)
> Add Romanian translations for #811

- package.json
To generate missing files when doing native builds
> Add gulp native command to npm postinstall task

- messages/_default.js
- messages/cs.js
- messages/de.js
- messages/es.js
- messages/fr.js
- messages/no.js
- messages/pt.js
- messages/ro.js
- src/browser/auth/Page.react.js
- src/browser/firebase/Page.react.js
- src/browser/home/Page.react.js
- src/browser/intl/Page.react.js
- src/browser/me/Page.react.js
- src/browser/todos/Page.react.js
> Replace titles with linksMessages

- webpack/makeConfig.js
todo: integrate gulp-sentry-release so with every commit new release is created
> feat: production source maps output

- package.json
> chore(package): update eslint to version 2.10.2

- package.json
- src/browser/main.js
> Add react-router-scroll

- src/common/auth/reducer.js
- src/common/configureReporting.js
- src/common/lib/redux-fields/actions.js
- src/common/lib/redux-fields/reducer.js
- src/common/lib/redux-firebase/actions.js
- src/common/lib/redux-firebase/queryFirebase.js
- src/common/users/reducer.js
> Prefix redux-fields and redux-firebase actions constants

- messages/_default.js
- src/browser/lib/Loading.react.js
- Use Helmet
- Localize messages
https://github.com/este/este/issues/789
> Localize Loading component

- messages/de.js
- messages/es.js
- messages/fr.js
- messages/pt.js
- messages/ro.js
> Closes #859

- README.md
I've added this, because I think it will make it easier to run Facebook login running on mobile, feel free to modify if you think it should be documented differently
> Added information about facebook login to README.md

- src/native/app/components/Text.react.js
- src/native/app/components/formatted.js
Partly solved #1046, but this fix will not work if the child is a function.
> Fix `Formatted*` to work with `TouchableHighlight`, Close #1046

- README.md
clone just last commit for shorter history and smaller project size
> Create app with 'git clone depth=1'

- README.md
- gulp/server.js
- gulp/support/args.js
Server restart can become pretty heavy. No need for it on every file change while working only on browser source.
> Added gulp -f for 'front'. Rebuilds only browser source on file change

- gulp/favicon-clean.js
- gulp/favicon.js
For issue https://github.com/este/este/issues/1147
> Clean generated favicons before regenerating

- src/common/app/actions.js
- src/common/users/actions.js
> Fix #1210 - rename stream according to the convention of redux-observable

- src/browser/app/App.js
> Make Footer sticky with Flex

- src/browser/app/components/Box.js
- src/browser/app/components/Button.js
- Added onClick prop to button
- Fixed justifyContent prop in Box component to be taken into account.
> Added onClick prop to button and fixed justifyContent prop in Box

- src/common/app/favicons/manifest.json
Adding background color to manifest to please lighthouse.
[https://developers.google.com/web/tools/lighthouse/audits/manifest-contains-background_color](https://developers.google.com/web/tools/lighthouse/audits/manifest-contains-background_color)
> Add backgroud_color to manifest

- package.json
- src/server/frontend/index.js
- src/server/frontend/render.js
- src/server/lib/errorHandler.js
- src/server/main.js
- webpack/server/main.js
If one day you plan to migrate Este from Express to Koa for server side, it is quiet easy to do.
This PR is just an example destined to people who want to use Este starter kit with Koa instead of Express.
> Este server with Koa v2.x.x

- circle.yml
> force circleci to use yarn

- README.md
Change folder when we git clone https://github.com/este/este.git
> Change folder name

- themes/typography.js
- themes/typography.test.js
Same as #1413 but working (hopefully) and with tests!
Sorry for the mixup, it's late here.
> Simplify typography calculations

- database/model.graphql
When trying to delete a Web, there was an error, in red, at the top, saying something like 
>  the change you are trying to make would violate the required relation.
> fix deletion bug with related models
