este/este

gulpfile.js, package.json, src/__tests__/getrandomstring.js
adds a gulp target: `gulp jest` which runs any jest tests found in `src/__tests__`
see previously https://github.com/steida/este-todomvc/pull/8
=> add jest support

webpack/makeconfig.js
stylus-loader is concrete loader, not a prefix
=> webpack: styleLoaders fix

src/server/render.js
You probably want to load GA only for production even. This is to prevent loading it when you set your GA id in `config.js`.
=> only load google analytics in production

src/lib/__tests__/getrandomstring.js
Fixes https://github.com/steida/este/issues/137.
Babel v 0.5 moves `require` statements transpired from `import` to the top of the file before the `dontMock` call. Always use `require` for test for now.
=> Fixed broken test.

src/server/frontend/index.js, src/server/frontend/render.js
This pull request simulates more real-life example by adding a general-purpose middleware that acts almost like e.g. https://www.npmjs.com/package/express-jwt.
Instead of having custom state logic hardcoded inside `render` which should just render files, we now fetch user details in a way every other project already does. That is, it's going to be easier for our users to understand the purpose as they are already familiar with this pattern.
=> Better custom state

src/client/intl/store.js
I standardized the output of msgs function to always return all keys defined in the Map for one List item. It solves step 3 in #246
=> Output standardization of msgs function

webpack/devserver.js
More info: https://github.com/webpack/webpack-dev-server/issues/151#issuecomment-104643642
With host = localhost is not possible to access webpack-dev-server from remote machines. With `0.0.0.0` you can just change the `localhost:8888` in `<script></script>`  to `NETWORK_ADDRESS:8888` and it works (without hot reloading though).
=> Localhost replaced by 0.0.0.0, then the dev mode works even from remote machines.

package.json, webpack/makeconfig.js
Actived just for the production build, because it's clashing with other outputs during the devel build.
=> Nyan progress bar for the webpack build

README.md
After bootstraping new este app `gulp` command does not work. Solution was to reinstall global gulp to newer version which supports babel. Add it to tips and trick, because it was pain to find it :)
=> Add tip for fixing old gulp version

gulpfile.babel.js
When using eslint.failAfterError, we get list of all eslint errors before the gulp task fails.
=> Show all eslint errors even if eslint fails.

webpack/makeconfig.js
This way it's easier to distinguish between SCSS and SASS files.
=> Fix Sass loader w/ indented syntax

README.md, circle.yml, package.json, web/gulpfile.babel.js, web/package.json
Because karma requires socket.io that does not support Node.js 4.0 - this produces warnings in `npm install` when node-gyp builds native modules. It has no impact on production and development because we do not use Karma at all, so decided to comment it out to get rid of these errors.
Karma dependencies were moved to custom `disabledDependencies` field just to not forget about them once we re-enable it back again.
=> Comment out karma temporarily

web/package.json
I was unable to start the web module and I was seeing many errors like the following:
```
ERROR in ./src/client/pages/auth.react.js
Module build failed: Error: ./web/src/client/pages/auth.react.js: babel-plugin-react-transform requires that you specify extras["react-transform"] in .babelrc or in your Babel Node API call options, and that it is an array.
```
I found that the config for this plugin had been updated in 196f0b14bb813b561d to reflect https://github.com/gaearon/babel-plugin-react-transform/releases/tag/v1.1.0, but the plugin itself had not.
=> Update babel-plugin-react-transform version

package.json, scripts/postInstall.sh
Use relative symlink instead of npm link to survive move from /tmp to /app. Thanks to symlinks, it still works nicely with babel require hook :)
PS. Not windows friendly, but let's close issues one by one.
The build script also skips installing react-native dependencies as there's no point in having them.
CC: @steida, test app deployed to https://shielded-gorge-2924.herokuapp.com/ without any issues.
=> Fixed Heroku deployments

gulpfile.babel.js
Using a `gulp build -p` will not set properly the `NODE_ENV` to production, which implies that the `babel-loader` would use react-transform nonetheless. So we need to call env before.
=> Add check for env before building webpack

gulpfile.babel.js, test/mochaRunCreator.js
HI problem is that: 
`gulp mocha` on failed test needs to return status code 1
`gulp mocha-watch` on failed test needs to print output to log
This PR is taken care of this
=> Fix Mocha and Mocha watch error handling

webpack/makeConfig.js
this enables caching for babel-loader and can speed up babel transforms 2x (as per docs)
=> adding cacheDirectory babel-loader param

package.json, src/browser/auth/__test__/Login.spec.js, test/mochaSetup.js, test/mochaTestHelper.js
And add one example usage.
Without this you never know if there was an error inside of a `then` in tests.
=> Report unhandled Promise rejections in tests

package.json
ESLint issue: https://github.com/eslint/eslint/issues/4508
Problem is with calling new with parens following
```js
const foo = new (Foo({dummy: true}))
=> Downgrade ESLint due to problem with new (Record({}))

src/server/frontend/assets.js
When you are starting Este by Passenger you are setting `passenger_startup_file` and then you are in different directory then expected.
By using `__dirname` you will get exact location of `assets.js` and then you can easily traverse to build directory
=> Fix assets paths when server started from different location than root of project

package.json, src/common/configureStore.js
The transformer option of redux-logger is deprecated in the latest minor version https://github.com/fcomb/redux-logger/releases/tag/2.1.1
=> Use stateTransformer instead of deprecated transformer in redux-logger

webpack/makeConfig.js
- Fixes issue where `process.env.WEB_ADDR` was only available on `server` rendering platform.
So now when you run:
```
WEB_ADDR=https://production-appName.herokuapp.com gulp 
```
It will properly be availble for mobile and browser as `process.env.WEB_ADDR`
=> Ensure webpack receives process.env.WEB_ADDR

package.json, src/browser/auth/Login.react.js, src/browser/auth/__test__/Login.spec.js, src/browser/createRoutes.js, src/browser/main.js, src/server/frontend/render.js
No warnings, no errors.
https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md
I thought that we could get rid of the RouteHandler and using `cloneElement`, but it turned out that the `<Router render={} />` which I wanted to use for this is for entirely different use case and does not help us.
=> Upgrade to React Router 2.0

src/common/components/RouterHandler.react.js
Having *props.route* property inherited from parent will result in error when using *routeWillLeave()* in child routes ([example](https://github.com/rackt/react-router/tree/master/examples/confirming-navigation)).
=> Change props.route to correct value

src/server/lib/errorHandler.js
According to [docs](http://expressjs.com/en/guide/error-handling.html): *"Define error-handling middleware functions in the same way as other middleware functions, except error-handling functions have four arguments instead of three: (err, req, res, next)."*
=> Fix errorHandler arity

src/common/app/actions.js, src/common/configureStore.js
Actions do not need access to `subscribe` or `replaceReducer`.
I think that actions usually need to know current state to compute next step. So current `state` is directly passed. (Small question: Would `getState` be better/safer?)
=> Safer DI middleware

webpack/makeConfig.js
When este application is placed inside `node_modules` directory the code transpilation does not work. All files are ignored because application's base directory path contains `node_modules` string.
I have encountered this problem while trying to pack and install application from file using npm (`npm pack`, `npm install <my_package>`.
=> babel loader - excluded only application modules

src/server/frontend/render.js
Solving issue #792. Use also ```req.query``` when the page is generated on the server.
=> Take care of req.query in render.js

src/native/app/App.react.js
Because the default 2/3 is ridiculously big.
=> Change default side menu width to 1/3 of screen

gulpfile.babel.js, package.json
gulp-shell is blacklisted, and it's faulty & half-abandoned plugin. For example, it fails if the process produces too much output to the console, probably because exhausting some limits on buffers.
Here I summarized a few alternatives:
http://stackoverflow.com/questions/37187069/how-to-easily-run-system-shell-task-command-in-gulp
I've tested this on windows, (since this was the reason for using `gulp-shell` in the first place) and at least `server-nodemon` works fine.
=> remove gulp-shell

src/common/lib/redux-fields/fields.js
@steida I like your implementation of `redux-fields`, but I encountered a small issue while using it together with `react-select`.
The implementation of `redux-select` sends the target directly to the `onChange` handler, but `redux-fields` is expecting that the target is wrapped in an event object first.
I prepared a small fix for it.
=> Fix react-fields onChange handler for react-select

webpack/makeConfig.js
There is typo in the name of webpack plugin. There is missing one r in Occur**r**enceOrderPlugin https://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin
=> fix typo in the name of webpack plugin

src/browser/intl/IntlPage.react.js
Following https://github.com/este/este/commit/b51807b624c9a72af93e325a31fa259f91f01a24
See [react-intl's API](https://github.com/yahoo/react-intl/wiki/API#date-formatting-apis)
=> Use long month for FormattedDate using a temporary patch for Intl.js

gulp/mocha-file.js, gulp/mocha.js, test/mochaRunCreator.js
Errors in mocha tests that were not handled and logged by mocha itself (thrown inside `it()`) just quietly terminated the process without any way to know what happened. Plus there was no need to log test errors again with gulp because mocha does it pretty well.
The fix takes in count the flow of the default `mocha` task, plus `mocha-file` and `mocha-watch`
=> Fixed logging of unhandled mocha errors

.babelrc, package.json
Removed "transform-react-inline-elements". It caused some issues when building production bundle.
https://phabricator.babeljs.io/T6946#anchor-80295
=> Closes #1010

android/app/src/main/java/com/este/MainActivity.java, android/app/src/main/java/com/este/MainApplication.java
There's a bug in the `MainApplication.java` file of the android project on line 32 (you will see the following if you try to run `react-native run-android`):
```
...\este-app\android\app\src\main\java\com\este\MainApplication.java:32: error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
new FBSDKPackage()
^
required: CallbackManager
found: no arguments
reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED
FAILURE: Build failed with an exception.
```
I've modified the file according to the readme for FBSDK https://github.com/facebook/react-native-fbsdk so this should be fixed now.
=> Fix for incorrect initialization of FBSDKPackage for Android

src/server/.babelrc, webpack/makeConfig.js
The transform-react-inline-elements dependency was not completely removed.
=> Fixed transform-react-inline-elements dependency removal.

README.md, package.json, src/browser/main.js, src/common/configureMiddleware.js, src/native/main.js
Use 'uuid' package in place of 'shortid', and switch to 'react-native-uuid' on react-native.
Fixes a problem in Windows where react-native would not load the 'crypto' package.
See este/este#1033
=> replace 'shortid' with 'uuid' / 'react-native-uuid'

src/native/app/components/formatted.js
The current wrapper for `Formatted*` in React Native doesn't support nested `Formatted*` such as below. This PR will fix this problem and make it work as normal.
```jsx
<FormattedMessage
id='app.greeting'
defaultMessage='{hello}, {name}!'
values={{
hello: <FormattedMessage id='app.hello' defaultMessage='Hello' />,
name: 'James',
}}
/>
```
=> Support for nested `Formatted*`

src/browser/app/Root.js
I'm not really sure why we use `pathname` here. The link talks about Int'l so I couldn't make the connection, but I guess it got something to do with the need to completely rebuild the components tree on path change (why the page don't changes without it?).
I do know that since the first `pathname` is always `null` (initial state) then on first load from server it always makes the whole app tree unmount and mount again. You can't really notice it with only stateless components, but when a stateful component mounts, unmounts and mounts again, its a big useless hassle.
I let myself offer this small change because I guess it's aligned with the original intent. Please ignore this pull request if I haven't got it correct.
=> using location.pathname as key to StaticRouter

webpack/makeConfig.js
I was trying to add font-awesome to my project and encountered problem with webpack not able to parse `.svg?v=4.7.0`, same thing with webfonts.
This PR should fix the issue while not break up anything else.
PS: I am not that good with expressions, double-check it please.
=> Fixed webpack SVG and webfont loader tests to match .svg?v=1.0 etc.

README.md
I recently noticed that somebody now has the username `rackt` after the account was (presumably) deleted when `rackt` repos were assigned to the `reactjs` organisation.
This person has also created a repo named `redux` so now all links to `rackt/redux` point to that (usually when a repo gets a new home, GH handles the redirecting).
Take a look: http://rackt.github.io/redux/
=> Update redux repo url in readme

package.json
Upgrade react-redux to v5 as it requires no code changes due to backward compatibility and claims significant performance improvements.[https://github.com/reactjs/react-redux/releases/tag/v5.0.0](https://github.com/reactjs/react-redux/releases/tag/v5.0.0)
=> Upgrade react-redux to v5

themes/typography.js
Gravely simplifies the typography calculations by using powers instead of reducing over an array.
This code should be more performant since we do not need to allocate arrays at all and it certainly has a clearer intent.
=> Simplify typography calculations

lib/cookie.js
Deleting a cookie(s) is not 100% reliable when only `name` of the cookie is provided. Cookie won't delete from nested URL path like `/dashboard/user/profile`. See [this SO answer](https://stackoverflow.com/questions/595228/how-can-i-delete-all-cookies-with-javascript/2421786#2421786) how to properly delete cookie.
In my project, adding `path` option during delete procedure fixed unreliable cookie(s) removal.
=> Setup cookies path when setting/deleting

.env.dev, README.md, database/docker-compose.yml, package.json
Init dev environment quicker with docker-compose, by just cloning the repo and then running `yarn docker:up`
Instead of having to do a `prisma init {APP_NAME}`, go through the setup, then copy the PRISMA_ENDPOINT, past the endpoint, then remove the new directory. 
Docker compose instantly spins up the prisma server and postgres database, and then surfaces the localhost:4466 endpoint.
Everything else including `yarn deploy:db` works exactly the same. But now you are running locally on machine, instead of a remote prisma server.
=> Add docker-compose for dev environment
